version: '3.8'

services:
  app:
    build: 
    ports:
      -"3000:3000"
    environment:
      - MONGO_URL=mondodb://mongo:27017/blog
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      -"27017:27017"